# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_context.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pyreach.common.proto_gen.object_ref_pb2 as object__ref__pb2
import pyreach.common.proto_gen.pose_pb2 as pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame_context.proto',
  package='robotics.messages',
  syntax='proto3',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66rame_context.proto\x12\x11robotics.messages\x1a\x10object_ref.proto\x1a\npose.proto\"t\n\x0c\x46rameContext\x12/\n\tframe_ref\x18\x01 \x01(\x0b\x32\x1c.robotics.messages.ObjectRef\x12\x33\n\x10world_pose_frame\x18\x02 \x01(\x0b\x32\x19.robotics.messages.Pose3d\"\x80\x01\n\x14\x46rameContextRelative\x12\x32\n\x0crelative_ref\x18\x01 \x01(\x0b\x32\x1c.robotics.messages.ObjectRef\x12\x34\n\x11parent_pose_frame\x18\x02 \x01(\x0b\x32\x19.robotics.messages.Pose3dB\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[object__ref__pb2.DESCRIPTOR,pose__pb2.DESCRIPTOR,])




_FRAMECONTEXT = _descriptor.Descriptor(
  name='FrameContext',
  full_name='robotics.messages.FrameContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_ref', full_name='robotics.messages.FrameContext.frame_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_pose_frame', full_name='robotics.messages.FrameContext.world_pose_frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=188,
)


_FRAMECONTEXTRELATIVE = _descriptor.Descriptor(
  name='FrameContextRelative',
  full_name='robotics.messages.FrameContextRelative',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='relative_ref', full_name='robotics.messages.FrameContextRelative.relative_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_pose_frame', full_name='robotics.messages.FrameContextRelative.parent_pose_frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=319,
)

_FRAMECONTEXT.fields_by_name['frame_ref'].message_type = object__ref__pb2._OBJECTREF
_FRAMECONTEXT.fields_by_name['world_pose_frame'].message_type = pose__pb2._POSE3D
_FRAMECONTEXTRELATIVE.fields_by_name['relative_ref'].message_type = object__ref__pb2._OBJECTREF
_FRAMECONTEXTRELATIVE.fields_by_name['parent_pose_frame'].message_type = pose__pb2._POSE3D
DESCRIPTOR.message_types_by_name['FrameContext'] = _FRAMECONTEXT
DESCRIPTOR.message_types_by_name['FrameContextRelative'] = _FRAMECONTEXTRELATIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameContext = _reflection.GeneratedProtocolMessageType('FrameContext', (_message.Message,), {
  'DESCRIPTOR' : _FRAMECONTEXT,
  '__module__' : 'frame_context_pb2'
  # @@protoc_insertion_point(class_scope:robotics.messages.FrameContext)
  })
_sym_db.RegisterMessage(FrameContext)

FrameContextRelative = _reflection.GeneratedProtocolMessageType('FrameContextRelative', (_message.Message,), {
  'DESCRIPTOR' : _FRAMECONTEXTRELATIVE,
  '__module__' : 'frame_context_pb2'
  # @@protoc_insertion_point(class_scope:robotics.messages.FrameContextRelative)
  })
_sym_db.RegisterMessage(FrameContextRelative)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
