# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: juggler.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pyreach.common.proto_gen.event_timestamp_pb2 as event__timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='juggler.proto',
  package='robotics.logging.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rjuggler.proto\x12\x19robotics.logging.messages\x1a\x15\x65vent_timestamp.proto\"\xac\x02\n\x12PhaseSpaceMetadata\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.robotics.logging.messages.PhaseSpaceMetadata.DeviceType\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x16\n\x0einternal_flags\x18\x03 \x01(\r\x12\x15\n\rinternal_time\x18\x04 \x01(\x03\x12\x15\n\rinternal_cond\x18\x05 \x01(\x02\x12&\n\x1eis_rigid_estimated_from_marker\x18\x06 \x01(\x08\"T\n\nDeviceType\x12\x17\n\x13\x44\x45VICE_TYPE_UNKNOWN\x10\x00\x12\x16\n\x12\x44\x45VICE_TYPE_MARKER\x10\x01\x12\x15\n\x11\x44\x45VICE_TYPE_RIGID\x10\x02\"\xdf\x02\n\rImageMetadata\x12W\n\x10\x65vent_timestamps\x18\x01 \x03(\x0b\x32=.robotics.logging.messages.ImageMetadata.EventTimestampsEntry\x12\x18\n\x0b\x66rame_index\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12\x1c\n\x0forigin_filepath\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1f\n\x12reference_frame_id\x18\x04 \x01(\tH\x02\x88\x01\x01\x1a\x61\n\x14\x45ventTimestampsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).robotics.logging.messages.EventTimestamp:\x02\x38\x01\x42\x0e\n\x0c_frame_indexB\x12\n\x10_origin_filepathB\x15\n\x13_reference_frame_id\"S\n\rVideoMetadata\x12\x42\n\x10\x66rame_timestamps\x18\x01 \x03(\x0b\x32(.robotics.logging.messages.ImageMetadatab\x06proto3'
  ,
  dependencies=[event__timestamp__pb2.DESCRIPTOR,])



_PHASESPACEMETADATA_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='robotics.logging.messages.PhaseSpaceMetadata.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MARKER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_RIGID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=284,
  serialized_end=368,
)
_sym_db.RegisterEnumDescriptor(_PHASESPACEMETADATA_DEVICETYPE)


_PHASESPACEMETADATA = _descriptor.Descriptor(
  name='PhaseSpaceMetadata',
  full_name='robotics.logging.messages.PhaseSpaceMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='robotics.logging.messages.PhaseSpaceMetadata.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='robotics.logging.messages.PhaseSpaceMetadata.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_flags', full_name='robotics.logging.messages.PhaseSpaceMetadata.internal_flags', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_time', full_name='robotics.logging.messages.PhaseSpaceMetadata.internal_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_cond', full_name='robotics.logging.messages.PhaseSpaceMetadata.internal_cond', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_rigid_estimated_from_marker', full_name='robotics.logging.messages.PhaseSpaceMetadata.is_rigid_estimated_from_marker', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHASESPACEMETADATA_DEVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=368,
)


_IMAGEMETADATA_EVENTTIMESTAMPSENTRY = _descriptor.Descriptor(
  name='EventTimestampsEntry',
  full_name='robotics.logging.messages.ImageMetadata.EventTimestampsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='robotics.logging.messages.ImageMetadata.EventTimestampsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='robotics.logging.messages.ImageMetadata.EventTimestampsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=663,
)

_IMAGEMETADATA = _descriptor.Descriptor(
  name='ImageMetadata',
  full_name='robotics.logging.messages.ImageMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_timestamps', full_name='robotics.logging.messages.ImageMetadata.event_timestamps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_index', full_name='robotics.logging.messages.ImageMetadata.frame_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin_filepath', full_name='robotics.logging.messages.ImageMetadata.origin_filepath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_frame_id', full_name='robotics.logging.messages.ImageMetadata.reference_frame_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IMAGEMETADATA_EVENTTIMESTAMPSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_frame_index', full_name='robotics.logging.messages.ImageMetadata._frame_index',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_origin_filepath', full_name='robotics.logging.messages.ImageMetadata._origin_filepath',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_reference_frame_id', full_name='robotics.logging.messages.ImageMetadata._reference_frame_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=371,
  serialized_end=722,
)


_VIDEOMETADATA = _descriptor.Descriptor(
  name='VideoMetadata',
  full_name='robotics.logging.messages.VideoMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_timestamps', full_name='robotics.logging.messages.VideoMetadata.frame_timestamps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=807,
)

_PHASESPACEMETADATA.fields_by_name['type'].enum_type = _PHASESPACEMETADATA_DEVICETYPE
_PHASESPACEMETADATA_DEVICETYPE.containing_type = _PHASESPACEMETADATA
_IMAGEMETADATA_EVENTTIMESTAMPSENTRY.fields_by_name['value'].message_type = event__timestamp__pb2._EVENTTIMESTAMP
_IMAGEMETADATA_EVENTTIMESTAMPSENTRY.containing_type = _IMAGEMETADATA
_IMAGEMETADATA.fields_by_name['event_timestamps'].message_type = _IMAGEMETADATA_EVENTTIMESTAMPSENTRY
_IMAGEMETADATA.oneofs_by_name['_frame_index'].fields.append(
  _IMAGEMETADATA.fields_by_name['frame_index'])
_IMAGEMETADATA.fields_by_name['frame_index'].containing_oneof = _IMAGEMETADATA.oneofs_by_name['_frame_index']
_IMAGEMETADATA.oneofs_by_name['_origin_filepath'].fields.append(
  _IMAGEMETADATA.fields_by_name['origin_filepath'])
_IMAGEMETADATA.fields_by_name['origin_filepath'].containing_oneof = _IMAGEMETADATA.oneofs_by_name['_origin_filepath']
_IMAGEMETADATA.oneofs_by_name['_reference_frame_id'].fields.append(
  _IMAGEMETADATA.fields_by_name['reference_frame_id'])
_IMAGEMETADATA.fields_by_name['reference_frame_id'].containing_oneof = _IMAGEMETADATA.oneofs_by_name['_reference_frame_id']
_VIDEOMETADATA.fields_by_name['frame_timestamps'].message_type = _IMAGEMETADATA
DESCRIPTOR.message_types_by_name['PhaseSpaceMetadata'] = _PHASESPACEMETADATA
DESCRIPTOR.message_types_by_name['ImageMetadata'] = _IMAGEMETADATA
DESCRIPTOR.message_types_by_name['VideoMetadata'] = _VIDEOMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhaseSpaceMetadata = _reflection.GeneratedProtocolMessageType('PhaseSpaceMetadata', (_message.Message,), {
  'DESCRIPTOR' : _PHASESPACEMETADATA,
  '__module__' : 'juggler_pb2'
  # @@protoc_insertion_point(class_scope:robotics.logging.messages.PhaseSpaceMetadata)
  })
_sym_db.RegisterMessage(PhaseSpaceMetadata)

ImageMetadata = _reflection.GeneratedProtocolMessageType('ImageMetadata', (_message.Message,), {

  'EventTimestampsEntry' : _reflection.GeneratedProtocolMessageType('EventTimestampsEntry', (_message.Message,), {
    'DESCRIPTOR' : _IMAGEMETADATA_EVENTTIMESTAMPSENTRY,
    '__module__' : 'juggler_pb2'
    # @@protoc_insertion_point(class_scope:robotics.logging.messages.ImageMetadata.EventTimestampsEntry)
    })
  ,
  'DESCRIPTOR' : _IMAGEMETADATA,
  '__module__' : 'juggler_pb2'
  # @@protoc_insertion_point(class_scope:robotics.logging.messages.ImageMetadata)
  })
_sym_db.RegisterMessage(ImageMetadata)
_sym_db.RegisterMessage(ImageMetadata.EventTimestampsEntry)

VideoMetadata = _reflection.GeneratedProtocolMessageType('VideoMetadata', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOMETADATA,
  '__module__' : 'juggler_pb2'
  # @@protoc_insertion_point(class_scope:robotics.logging.messages.VideoMetadata)
  })
_sym_db.RegisterMessage(VideoMetadata)


_IMAGEMETADATA_EVENTTIMESTAMPSENTRY._options = None
# @@protoc_insertion_point(module_scope)
