# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ClientToServer(google.protobuf.message.Message):
    """option go_package = ".;link";

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COMMAND_DATA_JSON_FIELD_NUMBER: builtins.int
    command_data_json: typing.Text = ...
    def __init__(self,
        *,
        command_data_json : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["command_data_json",b"command_data_json"]) -> None: ...
global___ClientToServer = ClientToServer

class ServerToClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEVICE_DATA_JSON_FIELD_NUMBER: builtins.int
    COLOR_DATA_FIELD_NUMBER: builtins.int
    DEPTH_DATA_FIELD_NUMBER: builtins.int
    device_data_json: typing.Text = ...
    color_data: builtins.bytes = ...
    depth_data: builtins.bytes = ...
    def __init__(self,
        *,
        device_data_json : typing.Text = ...,
        color_data : builtins.bytes = ...,
        depth_data : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["color_data",b"color_data","depth_data",b"depth_data","device_data_json",b"device_data_json"]) -> None: ...
global___ServerToClient = ServerToClient
