# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_ref.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import pyreach.common.proto_gen.object_id_pb2 as object__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_ref.proto',
  package='robotics.messages',
  syntax='proto3',
  serialized_options=b'\n#com.google.protos.robotics.messagesB\016ObjectRefProto\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10object_ref.proto\x12\x11robotics.messages\x1a\x19google/protobuf/any.proto\x1a\x0fobject_id.proto\"\x97\x02\n\tObjectRef\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32&.robotics.messages.ObjectId.ObjectType\x12+\n\x02id\x18\x03 \x01(\x0b\x32\x1f.robotics.messages.ObjectRef.Id\x1a\x98\x01\n\x02Id\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\x10\n\x06str_id\x18\x03 \x01(\tH\x00\x12\x10\n\x06int_id\x18\x04 \x01(\x03H\x00\x12\x30\n\tobject_id\x18\x05 \x01(\x0b\x32\x1b.robotics.messages.ObjectIdH\x00\x12\x0b\n\x03key\x18\x02 \x01(\tB\t\n\x07id_typeB8\n#com.google.protos.robotics.messagesB\x0eObjectRefProto\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,object__id__pb2.DESCRIPTOR,])




_OBJECTREF_ID = _descriptor.Descriptor(
  name='Id',
  full_name='robotics.messages.ObjectRef.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='robotics.messages.ObjectRef.Id.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str_id', full_name='robotics.messages.ObjectRef.Id.str_id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_id', full_name='robotics.messages.ObjectRef.Id.int_id', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='robotics.messages.ObjectRef.Id.object_id', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='robotics.messages.ObjectRef.Id.key', index=4,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id_type', full_name='robotics.messages.ObjectRef.Id.id_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=211,
  serialized_end=363,
)

_OBJECTREF = _descriptor.Descriptor(
  name='ObjectRef',
  full_name='robotics.messages.ObjectRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='robotics.messages.ObjectRef.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='robotics.messages.ObjectRef.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='robotics.messages.ObjectRef.id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OBJECTREF_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=363,
)

_OBJECTREF_ID.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_OBJECTREF_ID.fields_by_name['object_id'].message_type = object__id__pb2._OBJECTID
_OBJECTREF_ID.containing_type = _OBJECTREF
_OBJECTREF_ID.oneofs_by_name['id_type'].fields.append(
  _OBJECTREF_ID.fields_by_name['data'])
_OBJECTREF_ID.fields_by_name['data'].containing_oneof = _OBJECTREF_ID.oneofs_by_name['id_type']
_OBJECTREF_ID.oneofs_by_name['id_type'].fields.append(
  _OBJECTREF_ID.fields_by_name['str_id'])
_OBJECTREF_ID.fields_by_name['str_id'].containing_oneof = _OBJECTREF_ID.oneofs_by_name['id_type']
_OBJECTREF_ID.oneofs_by_name['id_type'].fields.append(
  _OBJECTREF_ID.fields_by_name['int_id'])
_OBJECTREF_ID.fields_by_name['int_id'].containing_oneof = _OBJECTREF_ID.oneofs_by_name['id_type']
_OBJECTREF_ID.oneofs_by_name['id_type'].fields.append(
  _OBJECTREF_ID.fields_by_name['object_id'])
_OBJECTREF_ID.fields_by_name['object_id'].containing_oneof = _OBJECTREF_ID.oneofs_by_name['id_type']
_OBJECTREF.fields_by_name['type'].enum_type = object__id__pb2._OBJECTID_OBJECTTYPE
_OBJECTREF.fields_by_name['id'].message_type = _OBJECTREF_ID
DESCRIPTOR.message_types_by_name['ObjectRef'] = _OBJECTREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectRef = _reflection.GeneratedProtocolMessageType('ObjectRef', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _OBJECTREF_ID,
    '__module__' : 'object_ref_pb2'
    # @@protoc_insertion_point(class_scope:robotics.messages.ObjectRef.Id)
    })
  ,
  'DESCRIPTOR' : _OBJECTREF,
  '__module__' : 'object_ref_pb2'
  # @@protoc_insertion_point(class_scope:robotics.messages.ObjectRef)
  })
_sym_db.RegisterMessage(ObjectRef)
_sym_db.RegisterMessage(ObjectRef.Id)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
