# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='robotics.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstats.proto\x12\x11robotics.messages\"\x98\x02\n\x05Stats\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12\x14\n\x0cstored_count\x18\x02 \x01(\x04\x12\x11\n\x04mean\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x12\n\x05stdev\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x10\n\x03min\x18\x05 \x01(\x01H\x02\x88\x01\x01\x12\x10\n\x03max\x18\x06 \x01(\x01H\x03\x88\x01\x01\x12\x34\n\tquantiles\x18\x07 \x03(\x0b\x32!.robotics.messages.Stats.Quantile\x12\x10\n\x03rms\x18\x08 \x01(\x01H\x04\x88\x01\x01\x1a,\n\x08Quantile\x12\x10\n\x08quantile\x18\x01 \x01(\x02\x12\x0e\n\x06sample\x18\x02 \x01(\x01\x42\x07\n\x05_meanB\x08\n\x06_stdevB\x06\n\x04_minB\x06\n\x04_maxB\x06\n\x04_rmsb\x06proto3'
)




_STATS_QUANTILE = _descriptor.Descriptor(
  name='Quantile',
  full_name='robotics.messages.Stats.Quantile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantile', full_name='robotics.messages.Stats.Quantile.quantile', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample', full_name='robotics.messages.Stats.Quantile.sample', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=272,
)

_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='robotics.messages.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='robotics.messages.Stats.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stored_count', full_name='robotics.messages.Stats.stored_count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='robotics.messages.Stats.mean', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stdev', full_name='robotics.messages.Stats.stdev', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='robotics.messages.Stats.min', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='robotics.messages.Stats.max', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantiles', full_name='robotics.messages.Stats.quantiles', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rms', full_name='robotics.messages.Stats.rms', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATS_QUANTILE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_mean', full_name='robotics.messages.Stats._mean',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_stdev', full_name='robotics.messages.Stats._stdev',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_min', full_name='robotics.messages.Stats._min',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_max', full_name='robotics.messages.Stats._max',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_rms', full_name='robotics.messages.Stats._rms',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=315,
)

_STATS_QUANTILE.containing_type = _STATS
_STATS.fields_by_name['quantiles'].message_type = _STATS_QUANTILE
_STATS.oneofs_by_name['_mean'].fields.append(
  _STATS.fields_by_name['mean'])
_STATS.fields_by_name['mean'].containing_oneof = _STATS.oneofs_by_name['_mean']
_STATS.oneofs_by_name['_stdev'].fields.append(
  _STATS.fields_by_name['stdev'])
_STATS.fields_by_name['stdev'].containing_oneof = _STATS.oneofs_by_name['_stdev']
_STATS.oneofs_by_name['_min'].fields.append(
  _STATS.fields_by_name['min'])
_STATS.fields_by_name['min'].containing_oneof = _STATS.oneofs_by_name['_min']
_STATS.oneofs_by_name['_max'].fields.append(
  _STATS.fields_by_name['max'])
_STATS.fields_by_name['max'].containing_oneof = _STATS.oneofs_by_name['_max']
_STATS.oneofs_by_name['_rms'].fields.append(
  _STATS.fields_by_name['rms'])
_STATS.fields_by_name['rms'].containing_oneof = _STATS.oneofs_by_name['_rms']
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {

  'Quantile' : _reflection.GeneratedProtocolMessageType('Quantile', (_message.Message,), {
    'DESCRIPTOR' : _STATS_QUANTILE,
    '__module__' : 'stats_pb2'
    # @@protoc_insertion_point(class_scope:robotics.messages.Stats.Quantile)
    })
  ,
  'DESCRIPTOR' : _STATS,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:robotics.messages.Stats)
  })
_sym_db.RegisterMessage(Stats)
_sym_db.RegisterMessage(Stats.Quantile)


# @@protoc_insertion_point(module_scope)
