# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workcell_io.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='workcell_io.proto',
  package='workcell',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11workcell_io.proto\x12\x08workcell\"\x8d\x01\n\x08IOConfig\x12(\n\ncapability\x18\x01 \x03(\x0b\x32\x14.workcell.Capability\x12\x10\n\x08io_space\x18\x02 \x03(\t\x12!\n\x07io_bank\x18\x03 \x03(\x0b\x32\x10.workcell.IOBank\x12\"\n\x07setting\x18\x04 \x03(\x0b\x32\x11.workcell.Setting\"\xa5\x01\n\nCapability\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x04 \x01(\t\x12!\n\x07io_type\x18\x05 \x01(\x0e\x32\x10.workcell.IOType\x12\x12\n\nfused_pins\x18\x06 \x01(\x08\x12\x1a\n\x03pin\x18\x07 \x03(\x0b\x32\r.workcell.Pin\"D\n\x03Pin\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05space\x18\x02 \x01(\t\x12\x15\n\ris_active_low\x18\x03 \x01(\x08\x12\t\n\x01n\x18\x04 \x01(\x03\"Q\n\x06IOBank\x12\r\n\x05space\x18\x01 \x01(\t\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.workcell.IOType\x12\x0b\n\x03min\x18\x03 \x01(\x03\x12\x0b\n\x03max\x18\x04 \x01(\x03\"b\n\x07Setting\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x0f\n\x05value\x18\x04 \x01(\tH\x00\x42\x0c\n\nvalue_type*\xa7\x01\n\x06IOType\x12\x1f\n\x1b\x43\x41PABILITY_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rDIGITAL_INPUT\x10\x01\x12\x12\n\x0e\x44IGITAL_OUTPUT\x10\x02\x12\x10\n\x0c\x41NALOG_INPUT\x10\x03\x12\x11\n\rANALOG_OUTPUT\x10\x04\x12\x11\n\rINTEGER_INPUT\x10\x05\x12\x12\n\x0eINTEGER_OUTPUT\x10\x06\x12\t\n\x05\x45VENT\x10\x07\x62\x06proto3'
)

_IOTYPE = _descriptor.EnumDescriptor(
  name='IOType',
  full_name='workcell.IOType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_INPUT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_OUTPUT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANALOG_INPUT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANALOG_OUTPUT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEGER_INPUT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEGER_OUTPUT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=597,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_IOTYPE)

IOType = enum_type_wrapper.EnumTypeWrapper(_IOTYPE)
CAPABILITY_TYPE_UNSPECIFIED = 0
DIGITAL_INPUT = 1
DIGITAL_OUTPUT = 2
ANALOG_INPUT = 3
ANALOG_OUTPUT = 4
INTEGER_INPUT = 5
INTEGER_OUTPUT = 6
EVENT = 7



_IOCONFIG = _descriptor.Descriptor(
  name='IOConfig',
  full_name='workcell.IOConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capability', full_name='workcell.IOConfig.capability', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='io_space', full_name='workcell.IOConfig.io_space', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='io_bank', full_name='workcell.IOConfig.io_bank', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setting', full_name='workcell.IOConfig.setting', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=173,
)


_CAPABILITY = _descriptor.Descriptor(
  name='Capability',
  full_name='workcell.Capability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='workcell.Capability.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='workcell.Capability.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='workcell.Capability.device_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='workcell.Capability.device_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='io_type', full_name='workcell.Capability.io_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fused_pins', full_name='workcell.Capability.fused_pins', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pin', full_name='workcell.Capability.pin', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=341,
)


_PIN = _descriptor.Descriptor(
  name='Pin',
  full_name='workcell.Pin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='workcell.Pin.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space', full_name='workcell.Pin.space', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_active_low', full_name='workcell.Pin.is_active_low', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='workcell.Pin.n', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=411,
)


_IOBANK = _descriptor.Descriptor(
  name='IOBank',
  full_name='workcell.IOBank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='space', full_name='workcell.IOBank.space', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='workcell.IOBank.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='workcell.IOBank.min', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='workcell.IOBank.max', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=494,
)


_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='workcell.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='workcell.Setting.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='workcell.Setting.int_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='workcell.Setting.float_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='workcell.Setting.value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_type', full_name='workcell.Setting.value_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=496,
  serialized_end=594,
)

_IOCONFIG.fields_by_name['capability'].message_type = _CAPABILITY
_IOCONFIG.fields_by_name['io_bank'].message_type = _IOBANK
_IOCONFIG.fields_by_name['setting'].message_type = _SETTING
_CAPABILITY.fields_by_name['io_type'].enum_type = _IOTYPE
_CAPABILITY.fields_by_name['pin'].message_type = _PIN
_IOBANK.fields_by_name['type'].enum_type = _IOTYPE
_SETTING.oneofs_by_name['value_type'].fields.append(
  _SETTING.fields_by_name['int_value'])
_SETTING.fields_by_name['int_value'].containing_oneof = _SETTING.oneofs_by_name['value_type']
_SETTING.oneofs_by_name['value_type'].fields.append(
  _SETTING.fields_by_name['float_value'])
_SETTING.fields_by_name['float_value'].containing_oneof = _SETTING.oneofs_by_name['value_type']
_SETTING.oneofs_by_name['value_type'].fields.append(
  _SETTING.fields_by_name['value'])
_SETTING.fields_by_name['value'].containing_oneof = _SETTING.oneofs_by_name['value_type']
DESCRIPTOR.message_types_by_name['IOConfig'] = _IOCONFIG
DESCRIPTOR.message_types_by_name['Capability'] = _CAPABILITY
DESCRIPTOR.message_types_by_name['Pin'] = _PIN
DESCRIPTOR.message_types_by_name['IOBank'] = _IOBANK
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.enum_types_by_name['IOType'] = _IOTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IOConfig = _reflection.GeneratedProtocolMessageType('IOConfig', (_message.Message,), {
  'DESCRIPTOR' : _IOCONFIG,
  '__module__' : 'workcell_io_pb2'
  # @@protoc_insertion_point(class_scope:workcell.IOConfig)
  })
_sym_db.RegisterMessage(IOConfig)

Capability = _reflection.GeneratedProtocolMessageType('Capability', (_message.Message,), {
  'DESCRIPTOR' : _CAPABILITY,
  '__module__' : 'workcell_io_pb2'
  # @@protoc_insertion_point(class_scope:workcell.Capability)
  })
_sym_db.RegisterMessage(Capability)

Pin = _reflection.GeneratedProtocolMessageType('Pin', (_message.Message,), {
  'DESCRIPTOR' : _PIN,
  '__module__' : 'workcell_io_pb2'
  # @@protoc_insertion_point(class_scope:workcell.Pin)
  })
_sym_db.RegisterMessage(Pin)

IOBank = _reflection.GeneratedProtocolMessageType('IOBank', (_message.Message,), {
  'DESCRIPTOR' : _IOBANK,
  '__module__' : 'workcell_io_pb2'
  # @@protoc_insertion_point(class_scope:workcell.IOBank)
  })
_sym_db.RegisterMessage(IOBank)

Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), {
  'DESCRIPTOR' : _SETTING,
  '__module__' : 'workcell_io_pb2'
  # @@protoc_insertion_point(class_scope:workcell.Setting)
  })
_sym_db.RegisterMessage(Setting)


# @@protoc_insertion_point(module_scope)
